# This is a basic workflow to help you get started with Actions

name: Deploy On Repo Dispatch

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: [merge-content]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mergeContent:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Clone submodules
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_REPO_HOOK_TOKEN }}
        submodules: true
    
    - name: Update submodules content
      run: |
        git submodule update --remote --recursive  
    - run: git pull
          
    - name: Update submodules index
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Required
        commit_message: Update submodule        

        # Optional commit user and author settings
        commit_user_name: My GitHub Actions Bot
        commit_user_email: dpnminh@gmail.com # to change
        commit_author: My GitHub Actions Bot <actions@github.com>
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v19.0.1+4
      with:
        vercel-token: ${{ secrets.PAT_ZEIT_DEPLOY }} # Required
        vercel-args: '--prod' #Optional
        vercel-org-id: ${{ secrets.ZEIT_ORG_ID}}  #Required
        vercel-project-id: ${{ secrets.ZEIT_PROJECT_ID}} #Required 
   # - name: Netlify Deploy
   #   uses: jsmrcaga/action-netlify-deploy@v1.2.0
   #   with:
   #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
   #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_APP_ID }}
    - name: Tweet about it
      if: "!contains(github.event.client_payload.message, 'skip twitter') && !contains(github.event.client_payload.message, 'Merge pull request')"
      uses: ethomson/send-tweet-action@v1
      with:
        status: "ðŸš€ ${{ github.event.client_payload.message }}"
        consumer-key: ${{ secrets.TWITTER_API_KEY }}
        consumer-secret: ${{ secrets.TWITTER_API__SECRET_KEY }}
        access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
